version: '3'
services:
  nginx:
    build:
        context: .
        dockerfile: ./docker/nginx/Dockerfile
    ports:
        - "8080:80"
    volumes:
        - .:/app:cached
        - ./docker/conf/nginx/site.conf:/etc/nginx/conf.d/default.conf:cached
    links:
        - php_1
        - php_2
        - php_3
  php_1:
    build:
        context: .
        dockerfile: ./docker/php/Dockerfile
    volumes:
        - .:/app:cached
        - ./docker/conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
    environment:
      - NAME=php_1
  php_2:
    build:
        context: .
        dockerfile: ./docker/php/Dockerfile
    volumes:
        - .:/app:cached
        - ./docker/conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
    environment:
      - NAME=php_2
  php_3:
    build:
        context: .
        dockerfile: ./docker/php/Dockerfile
    volumes:
        - .:/app:cached
        - ./docker/conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
    environment:
      - NAME=php_3
